name: hankwong
age: 18
password: 1234567
header: '{cipher}1eef53f50c547f0b91c51778b711adfd4d464407055e9e2125f7794bec96d68a'

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

spring:
  datasource:
    jdbc-url: jdbc:mysql://94.191.6.149:3306/test?useUnicode=true&serverTimezone=GMT%2B8&charecterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: abcd_123