name: hankwong
age: 18
password: 123456
header: order

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

spring:
  datasource:
    jdbc-url: jdbc:mysql://94.191.6.149:3306/test?useUnicode=true&serverTimezone=GMT%2B8&charecterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: abcd_123